
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(204, 10069);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(205, 10069);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(206, 10069);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(10, 112);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(195, 11581);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(411, 11655);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(23, 1178);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(362, 11956);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(84, 121);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(155, 12134);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(24, 1251);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(218, 12548);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(320, 12548);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(62, 1258);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(63, 1258);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(186, 12678);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(187, 12678);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(188, 12678);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(189, 12678);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(306, 12698);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(4, 13);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(38, 13);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(358, 13);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(211, 13207);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(56, 1355);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(88, 1355);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(141, 1390);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(177, 14476);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(178, 14476);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(208, 14514);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(209, 14514);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(179, 14723);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(276, 14723);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(270, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(271, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(281, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(282, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(283, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(285, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(331, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(343, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(402, 14936);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(151, 1497);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(162, 1497);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(163, 1497);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(164, 1497);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(37, 1514);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(12, 153);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(301, 15561);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(302, 15561);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(303, 15561);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(199, 15683);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(200, 15683);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(257, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(258, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(259, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(260, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(261, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(262, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(263, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(264, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(265, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(266, 15733);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(220, 15795);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(21, 16);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(33, 16);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(35, 16);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(60, 16);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(70, 16);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(149, 16);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(360, 16);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(39, 1608);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(40, 1634);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(43, 1634);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(44, 1634);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(45, 1634);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(46, 1634);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(48, 1634);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(49, 1634);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(50, 1634);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(235, 16607);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(314, 16690);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(52, 1701);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(53, 1701);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(55, 1701);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(213, 17058);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(214, 17058);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(212, 17116);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(51, 1730);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(368, 17303);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(221, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(222, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(223, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(224, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(225, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(226, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(227, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(228, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(229, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(230, 17845);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(345, 18);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(231, 18068);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(69, 1832);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(58, 1844);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(59, 1844);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(321, 18916);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(378, 18916);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(241, 18931);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(242, 18931);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(243, 18931);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(244, 18931);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(245, 18931);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(246, 18931);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(247, 18931);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(233, 18933);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(240, 18933);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(383, 18968);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(313, 19006);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(64, 1945);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(248, 19504);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(253, 19504);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(267, 19504);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(14, 2);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(15, 2);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(109, 20);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(315, 20122);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(279, 20153);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(275, 20214);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(312, 20358);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(401, 20358);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(286, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(287, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(288, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(289, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(290, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(291, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(379, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(418, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(419, 20384);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(304, 20861);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(323, 20993);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(361, 20993);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(103, 2109);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(427, 21105);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(324, 21242);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(325, 21242);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(326, 21242);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(417, 21243);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(329, 21504);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(330, 21504);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(78, 22);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(148, 22);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(384, 22219);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(366, 22240);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(367, 22240);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(425, 22395);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(426, 22395);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(396, 22731);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(397, 22731);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(398, 22731);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(399, 22731);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(400, 22731);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(316, 22954);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(317, 22994);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(318, 22994);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(319, 22994);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(322, 23655);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(443, 25);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(22, 26);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(365, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(369, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(370, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(371, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(423, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(424, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(437, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(438, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(439, 2642);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(72, 2665);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(421, 286);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(165, 298);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(1, 30);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(28, 30);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(307, 30);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(433, 30);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(441, 30);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(83, 345);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(176, 358);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(180, 3583);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(181, 3583);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(182, 3583);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(183, 3583);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(184, 3583);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(185, 3583);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(327, 36080);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(114, 3920);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(31, 43);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(41, 43);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(359, 43403);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(36, 45);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(310, 453);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(311, 4533);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(82, 47);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(277, 4706);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(309, 4706);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(167, 4707);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(207, 4707);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(217, 4707);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(16, 5);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(20, 5);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(210, 5);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(428, 5);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(429, 5);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(430, 5);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(431, 5);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(363, 58327);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(364, 58327);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(85, 589);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(389, 60031);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(372, 60333);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(373, 60333);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(374, 60333);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(375, 60333);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(376, 60333);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(380, 60693);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(381, 60693);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(412, 61095);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(388, 61236);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(422, 61510);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(406, 61532);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(407, 61532);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(408, 61532);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(409, 61571);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(413, 61678);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(414, 61678);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(415, 61678);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(416, 61765);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(420, 61765);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(440, 61818);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(25, 62);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(26, 62);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(27, 62);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(29, 62);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(30, 62);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(42, 62);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(432, 62142);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(435, 6386);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(436, 6386);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(377, 654);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(382, 654);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(387, 654);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(442, 6595);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(232, 6658);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(194, 6731);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(203, 6731);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(308, 6731);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(390, 6902);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(391, 6902);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(392, 6902);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(393, 6902);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(394, 6902);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(17, 70);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(18, 70);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(61, 70);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(219, 70);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(9, 71);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(154, 7248);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(268, 7248);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(172, 7251);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(173, 7251);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(32, 749);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(104, 7562);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(99, 7581);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(100, 7581);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(101, 7581);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(102, 7581);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(105, 7581);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(106, 7581);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(89, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(90, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(91, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(92, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(93, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(94, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(95, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(96, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(97, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(98, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(107, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(108, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(119, 7582);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(113, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(157, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(158, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(293, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(294, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(295, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(296, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(297, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(298, 7598);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(215, 7799);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(216, 7799);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(299, 7799);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(8, 80);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(111, 8393);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(197, 8460);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(198, 8460);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(115, 8678);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(6, 9);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(54, 9);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(273, 9406);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(274, 9406);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(117, 9535);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(122, 9758);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(130, 9758);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(300, 976);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(65, 979);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(67, 979);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(68, 979);
INSERT INTO favoritos(cod_workflow_favorito, cod_usuario)VALUES(71, 982);
 
 /*inserte sistema gerenciador de workflow*/
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Taverna 1' , 'application/vnd.taverna.scufl+xml' , 'http://www.taverna.org.uk' , 1);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Vistrails' , 'application/octet-stream' , '' , 101);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Taverna 3' , 'application/vnd.taverna.scufl2.workflow-bundle' , 'http://www.taverna.org.uk' , 102);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Taverna 3 wfbundle' , 'application/octet-stream' , 'http://orcid.org/0000-0001-9842-9718' , 103);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Talend' , 'application/x-zip-compressed' , 'http://bio2rdf.org' , 106);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-ruby' , 'application/x-ruby' , '' , 108);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('geneXplain type' , 'application/octet-stream' , 'http://genexplain.com/' , 109);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Pipeline Pilot' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 11);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/binary' , 'application/binary' , 'http://www.ms-utils.org' , 113);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('SimileXMLv3' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 12);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Excel 2007 Macro-Enabled Workbook' , 'application/vnd.ms-excel.sheet.macroEnabled.12' , 'http://www.ecs.soton.ac.uk/people/dgc' , 13);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Kepler' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 14);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Nimrod Parameter Sweep' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 15);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Taverna 2' , 'application/vnd.taverna.t2flow+xml' , 'http://www.taverna.org.uk' , 2);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Binary data' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 21);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Adobe PDF' , 'application/pdf' , 'http://www.ecs.soton.ac.uk/people/dgc' , 23);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('AVI video' , 'video/x-msvideo' , 'http://www.ecs.soton.ac.uk/people/dgc' , 28);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Trident (XOML)' , 'application/xaml+xml' , '' , 3);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Trident (Package)' , 'application/octet-stream' , '' , 4);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('XProc' , 'audio/x-scpls' , 'http://plindenbaum.blogspot.com' , 45);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('BioExtract Server' , 'application/xml' , 'http://bioextract.org' , 46);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/mspowerpoint' , 'application/mspowerpoint' , 'http://www.mygrid.org.uk' , 47);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/vnd.oasis.opendocument.presentation' , 'application/vnd.oasis.opendocument.presentation' , 'http://www.inf.ufrgs.br/~rcpinto' , 49);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Chemistry Plan' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 5);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' , 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' , 'http://bioinfo.icapture.ubc.ca' , 50);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Bioclipse Scripting Language' , 'application/javascript' , 'http://chem-bla-ics.blogspot.com/' , 51);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Triana' , 'text/xml' , 'http://www.ebi.ac.uk/' , 52);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Diagram' , 'image/jpeg' , '' , 53);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Document' , 'application/msword' , '' , 54);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-zip-compressed' , 'application/x-zip-compressed' , 'http://www.saltlux.com' , 55);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-zip' , 'application/x-zip' , 'http://www.cs.man.ac.uk/~pmissier/' , 56);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/octetstream' , 'application/octetstream' , 'http://sites.google.com/site/jacekbuczny' , 57);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-download' , 'application/x-download' , 'http://www.biosemantics.org' , 58);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-perl' , 'application/x-perl' , 'http://www.sgtp.net/AndreaSplendiani/' , 59);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Makefile' , 'application/x-makefile' , 'http://www.ecs.soton.ac.uk/people/dgc' , 6);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('SPARQL' , 'application/octet-stream' , 'http://chem-bla-ics.blogspot.com/' , 60);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-gzip' , 'application/x-gzip' , '' , 61);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('RapidMiner' , 'application/vnd.rapidminer.rmp+zip' , 'http://rapid-i.com' , 62);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-gzip-compressed' , 'application/x-gzip-compressed' , 'http://www.ondex.org' , 63);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('LabTrove Template' , 'application/xml' , '' , 67);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/unknown' , 'application/unknown' , 'http://www.cs.man.ac.uk/~pmissier/' , 69);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('GWorkflowDL' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 7);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('htm' , 'text/html' , '' , 70);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Galaxy' , 'application/vnd.galaxy.workflow+json' , 'http://www.ecs.soton.ac.uk/people/dgc' , 73);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/force-download' , 'application/vnd.galaxy.workflow+xml' , '' , 74);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-java-archive' , 'application/x-java-archive' , '' , 75);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('KNIME' , 'application/x-zip-compressed' , 'http://www.dirkgorissen.com' , 76);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/msexcel' , 'application/msexcel' , '' , 78);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Manual Web Service' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 8);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('PDF' , 'application/pdf' , 'http://www.oerc.ox.ac.uk/people/dder' , 80);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('LONI Pipeline' , 'application/octet-stream' , 'http://pipeline.loni.usc.edu/' , 83);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-shellscript' , 'application/x-shellscript' , 'http://www.ars.usda.gov/Main/docs.htm?docid=5819' , 84);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Gwendia' , 'application/octet-stream' , 'http://www.creatis.insa-lyon.fr/~glatard' , 85);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/vnd.openxmlformats-officedocument.presentationml.slideshow' , 'application/vnd.openxmlformats-officedocument.presentationml.slideshow' , '' , 88);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('applicaton/octet-stream' , 'applicaton/octet-stream' , '' , 89);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('WSVLAM' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 9);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('test' , 'text/plain' , 'http://plindenbaum.blogspot.com' , 90);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Mobyle' , 'text/xml' , 'http://lipm-bioinfo.toulouse.inra.fr' , 91);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-crossover-xls' , 'application/x-crossover-xls' , 'http://kabohemi.mysite.syr.edu' , 92);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('OCR and text edit distance' , 'application/octet-stream' , '' , 94);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Tesla' , 'application/octet-stream' , 'http://tesla.spinfo.uni-koeln.de' , 96);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/publicationlist' , 'application/publicationlist' , '' , 97);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/xslt+xml' , 'application/xslt+xml' , '' , 98);
 