
 /*inserte sistema gerenciador de workflow*/
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Taverna 1' , 'application/vnd.taverna.scufl+xml' , 'http://www.taverna.org.uk' , 1);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Vistrails' , 'application/octet-stream' , '' , 101);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Taverna 3' , 'application/vnd.taverna.scufl2.workflow-bundle' , 'http://www.taverna.org.uk' , 102);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Taverna 3 wfbundle' , 'application/octet-stream' , 'http://orcid.org/0000-0001-9842-9718' , 103);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Talend' , 'application/x-zip-compressed' , 'http://bio2rdf.org' , 106);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-ruby' , 'application/x-ruby' , '' , 108);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('geneXplain type' , 'application/octet-stream' , 'http://genexplain.com/' , 109);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Pipeline Pilot' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 11);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/binary' , 'application/binary' , 'http://www.ms-utils.org' , 113);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('SimileXMLv3' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 12);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Excel 2007 Macro-Enabled Workbook' , 'application/vnd.ms-excel.sheet.macroEnabled.12' , 'http://www.ecs.soton.ac.uk/people/dgc' , 13);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Kepler' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 14);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Nimrod Parameter Sweep' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 15);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Taverna 2' , 'application/vnd.taverna.t2flow+xml' , 'http://www.taverna.org.uk' , 2);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Binary data' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 21);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Adobe PDF' , 'application/pdf' , 'http://www.ecs.soton.ac.uk/people/dgc' , 23);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('AVI video' , 'video/x-msvideo' , 'http://www.ecs.soton.ac.uk/people/dgc' , 28);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Trident (XOML)' , 'application/xaml+xml' , '' , 3);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Trident (Package)' , 'application/octet-stream' , '' , 4);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('XProc' , 'audio/x-scpls' , 'http://plindenbaum.blogspot.com' , 45);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('BioExtract Server' , 'application/xml' , 'http://bioextract.org' , 46);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/mspowerpoint' , 'application/mspowerpoint' , 'http://www.mygrid.org.uk' , 47);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/vnd.oasis.opendocument.presentation' , 'application/vnd.oasis.opendocument.presentation' , 'http://www.inf.ufrgs.br/~rcpinto' , 49);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Chemistry Plan' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 5);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' , 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' , 'http://bioinfo.icapture.ubc.ca' , 50);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Bioclipse Scripting Language' , 'application/javascript' , 'http://chem-bla-ics.blogspot.com/' , 51);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Triana' , 'text/xml' , 'http://www.ebi.ac.uk/' , 52);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Diagram' , 'image/jpeg' , '' , 53);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Document' , 'application/msword' , '' , 54);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-zip-compressed' , 'application/x-zip-compressed' , 'http://www.saltlux.com' , 55);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-zip' , 'application/x-zip' , 'http://www.cs.man.ac.uk/~pmissier/' , 56);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/octetstream' , 'application/octetstream' , 'http://sites.google.com/site/jacekbuczny' , 57);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-download' , 'application/x-download' , 'http://www.biosemantics.org' , 58);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-perl' , 'application/x-perl' , 'http://www.sgtp.net/AndreaSplendiani/' , 59);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Makefile' , 'application/x-makefile' , 'http://www.ecs.soton.ac.uk/people/dgc' , 6);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('SPARQL' , 'application/octet-stream' , 'http://chem-bla-ics.blogspot.com/' , 60);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-gzip' , 'application/x-gzip' , '' , 61);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('RapidMiner' , 'application/vnd.rapidminer.rmp+zip' , 'http://rapid-i.com' , 62);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-gzip-compressed' , 'application/x-gzip-compressed' , 'http://www.ondex.org' , 63);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('LabTrove Template' , 'application/xml' , '' , 67);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/unknown' , 'application/unknown' , 'http://www.cs.man.ac.uk/~pmissier/' , 69);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('GWorkflowDL' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 7);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('htm' , 'text/html' , '' , 70);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Galaxy' , 'application/vnd.galaxy.workflow+json' , 'http://www.ecs.soton.ac.uk/people/dgc' , 73);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/force-download' , 'application/vnd.galaxy.workflow+xml' , '' , 74);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-java-archive' , 'application/x-java-archive' , '' , 75);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('KNIME' , 'application/x-zip-compressed' , 'http://www.dirkgorissen.com' , 76);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/msexcel' , 'application/msexcel' , '' , 78);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Manual Web Service' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 8);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('PDF' , 'application/pdf' , 'http://www.oerc.ox.ac.uk/people/dder' , 80);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('LONI Pipeline' , 'application/octet-stream' , 'http://pipeline.loni.usc.edu/' , 83);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-shellscript' , 'application/x-shellscript' , 'http://www.ars.usda.gov/Main/docs.htm?docid=5819' , 84);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Gwendia' , 'application/octet-stream' , 'http://www.creatis.insa-lyon.fr/~glatard' , 85);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/vnd.openxmlformats-officedocument.presentationml.slideshow' , 'application/vnd.openxmlformats-officedocument.presentationml.slideshow' , '' , 88);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('applicaton/octet-stream' , 'applicaton/octet-stream' , '' , 89);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('WSVLAM' , 'application/octet-stream' , 'http://www.ecs.soton.ac.uk/people/dgc' , 9);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('test' , 'text/plain' , 'http://plindenbaum.blogspot.com' , 90);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Mobyle' , 'text/xml' , 'http://lipm-bioinfo.toulouse.inra.fr' , 91);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/x-crossover-xls' , 'application/x-crossover-xls' , 'http://kabohemi.mysite.syr.edu' , 92);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('OCR and text edit distance' , 'application/octet-stream' , '' , 94);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('Tesla' , 'application/octet-stream' , 'http://tesla.spinfo.uni-koeln.de' , 96);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/publicationlist' , 'application/publicationlist' , '' , 97);
 INSERT INTO sistema_gerenciador_workflows_cientificos (nomesgwc, mime_type, homepage, arquivo) VALUES('application/xslt+xml' , 'application/xslt+xml' , '' , 98);
 
